name: Test

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: uv sync
    - name: Lint
      run: make lint
    - name: Typecheck
      run: make typecheck
    - name: Test with pytest
      run: make coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
